### ISSUE TITLE
POAP botting section

### ISSUE THREAD

**Issue by liminal-dog** [fmeiraf/poap_analysis#1]
Love the section on potential "botting" to collect POAPs.

I hate to nitpick, but for this line...
`We can see from above that the person event mints events that in different cities in the same day.. sounds like a bot action.` 

Were some of these events in "different cities" virtual events? Just want to cover our bases here.

**Comment by fmeiraf** [comment]
Added a better example for this, at the same time cleaning some unnecessary code and making the thought process clearer. 

Commit: https://github.com/fmeiraf/poap_analysis/commit/4b05c8767e8d54d71bafbe31e4ecefda1304fb03
