### ISSUE TITLE
First Event Section                

### ISSUE THREAD

**Issue by liminal-dog** [fmeiraf/poap_analysis#2]
I'm kind of confused by what this cell is supposed to communicate
![Screen Shot 2022-02-21 at 10 25 38 PM](https://user-images.githubusercontent.com/89407579/155074935-6c9e497a-fc71-4b05-a5ad-49d7e3cc8f5f.png)

Versus this cell
![Screen Shot 2022-02-21 at 10 25 59 PM](https://user-images.githubusercontent.com/89407579/155074971-76d6ab26-f749-461d-83fd-c6dc0f404555.png)

The Beanie event has a different count for wallets in each.

**Comment by fmeiraf** [comment]
The rank on the top is divided by the top%s based on the number of mints, the rank down there is an overall rank (putting everyone together). This section was not clear enough so I added more descriptions and also I made the second table to show only the top 30% (altogether) so this second rank has more utility too - based on the following sections. 

commit: https://github.com/fmeiraf/poap_analysis/commit/324776aa418457fb55e69fb2d976e25ebf0e302e
