### ISSUE TITLE
DAO overlap

### ISSUE THREAD

**Issue by liminal-dog** [fmeiraf/poap_analysis#3]
![Screen Shot 2022-02-21 at 10 27 02 PM](https://user-images.githubusercontent.com/89407579/155075079-c605e4a0-6352-4187-b41d-a97f05bfdb6a.png)

I'm surprised there's so little overlap. For instance, you'd think Diamond DAO would show up here, since we have POAPs. Is it not reporting on DAOs where we don't have a name?

**Comment by liminal-dog** [comment]
Yup that's it. Many DAOs don't have names in the legacy Chainverse DB. 

```SELECT 	memb.*,
		dao.name dao_name,
		dao.address dao_address,
		dao.inactive dao_inactive,
		dao.created_at dao_created_at,
		dao.chain dao_chain```

**Comment by liminal-dog** [comment]
We also don't seem to be gathering the (500k+) wallets that have voted on Snapshot proposals.

```SELECT  sv.*,
        sp.name space_name,
		sp.about space_about,
		sp.location space_location
FROM snapshot.votes sv
    INNER JOIN snapshot.spaces sp ON (sv.space_id = sp.id)```

**Comment by fmeiraf** [comment]
As we talked on Discord I will be closing this one.
