### ISSUE TITLE
Investigate DAO relationships of holders

### ISSUE THREAD

**Issue by liminal-dog** [fmeiraf/poap_analysis#4]
```DAO relationship: this is the part that becomes difficult once we don't have issuer identification. It's hard to associate events to DAOs only using names, descriptions and URLs. I personally tried all these approaches but none of them showed satisfactory results.```

Can we check whether or not the POAP holders (versus the issuers) belong to certain DAOs?

**Comment by fmeiraf** [comment]
Created a new section to answer this here:

https://github.com/fmeiraf/poap_analysis/commit/962121eed46a026e5d2d1806f6e4696372cf5bd2
